{{- $webClient := index .Values "web-client" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s.web-client.conf" (include "medea-demo.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "medea-demo.chart" . | quote }}
    app.kubernetes.io/name: {{ include "medea-demo.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: web-client
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  nginx.vh.conf: |
  {{- if $webClient.conf.nginx }}
    {{- $webClient.conf.nginx | nindent 4 }}
  {{- else }}
    {{- tpl (.Files.Get "conf/nginx.vh.conf") . | nindent 4 }}
  {{- end }}
