{{- $controlApi := index .Values "control-api" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "medea-demo.fullname" . }}-control-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "medea-demo.chart" . }}
    app.kubernetes.io/name: {{ template "medea-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: control-api
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $controlApi.deployment.replicas }}
  revisionHistoryLimit: {{ $controlApi.deployment.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "medea-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "medea-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/component: control-api
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/conf: {{ pick (include (print $.Template.BasePath "/configmap.web-client.yaml") . | fromYaml) "data" | toYaml | sha256sum }}
      {{- with $controlApi.deployment.revision }}
        revision: {{ . | quote }}
      {{- end }}
      {{- with $controlApi.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with $controlApi.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $controlApi.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: control-api
          image: "{{ $controlApi.image.repository }}:{{ $controlApi.image.tag }}"
          imagePullPolicy: {{ $controlApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $controlApi.conf.bind_port }}
              protocol: TCP
        {{- with $controlApi.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
