{{- $webClient := index .Values "web-client" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "medea-demo.fullname" . }}-web-client
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "medea-demo.chart" . }}
    app.kubernetes.io/name: {{ template "medea-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: web-client
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $webClient.deployment.replicas }}
  revisionHistoryLimit: {{ $webClient.deployment.revisionHistoryLimit }}
{{- if gt (int $webClient.deployment.replicas) 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "medea-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: web-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "medea-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/component: web-client
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/conf: {{ pick (include (print $.Template.BasePath "/configmap.web-client.yaml") . | fromYaml) "data" | toYaml | sha256sum }}
      {{- with $webClient.deployment.revision }}
        revision: {{ . | quote }}
      {{- end }}
      {{- with $webClient.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with $webClient.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $webClient.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: demo
          image: "{{ $webClient.image.repository }}:{{ $webClient.image.tag }}"
          imagePullPolicy: {{ $webClient.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: conf
              subPath: nginx.vh.conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
        {{- with $webClient.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
      volumes:
        - name: conf
          configMap:
            name: {{ template "medea-demo.fullname" . }}.web-client.conf
