{{- if .Values.ingress.enabled -}}
{{- range $host := .Values.ingress.hosts }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ printf "%s.%s" (include "medea-demo.fullname" $) $host | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "medea-demo.chart" $ | quote }}
    app.kubernetes.io/name: {{ include "medea-demo.name" $ | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/component: ingress
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- if and $.Values.ingress.tls.enabled $.Values.ingress.tls.auto }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
  {{- if not $.Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- end }}
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /control-api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-server" (include "medea-demo.fullname" $) | quote }}
                port:
                  name: control-http
          - path: /ws
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-server" (include "medea-demo.fullname" $) | quote }}
                port:
                  name: http
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-web-client" (include "medea-demo.fullname" $) | quote }}
                port:
                  name: http
{{- if $.Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ if $.Values.ingress.tls.auto -}}
                    {{ printf "%s.tls" ($host | trunc 48) | quote }}
                  {{- else -}}
                    {{ required (print `TLS Secret name must be specified for host ` $host ` !`) (index $.Values.ingress.tls.secretName $host) | quote }}
                  {{- end }}
      hosts:
        - {{ $host | quote }}
{{- end }}
{{- end }}
{{- end -}}
