{{- if .Values.ingress.tls.enabled -}}
{{- if not .Values.ingress.tls.auto -}}
{{- if hasKey .Values.ingress.tls.secretName "medea-demo.test" -}}
{{- if eq (index .Values.ingress.tls.secretName "medea-demo.test") "medea-demo.test.tls" -}}
kind: Secret
apiVersion: v1
metadata:
  name: medea-demo.test.tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "medea-demo.chart" $ }}
    app.kubernetes.io/name: {{ include "medea-demo.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: ingress
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "default/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "default/tls.key" | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
