kind: Service
apiVersion: v1
metadata:
  name: {{ template "medea-demo.fullname" . }}-web-client
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "medea-demo.chart" . }}
    app.kubernetes.io/name: {{ template "medea-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: web-client
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "medea-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: web-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
