version: "2"

services:
  control-api-mock:
    container_name: medea-control-api-mock
    build:
      context: .
      dockerfile: ./mock/control-api/Dockerfile
    depends_on: ["medea"]
    image: ${MEDEA_CONTROL_MOCK_IMAGE_NAME}:${MEDEA_CONTROL_MOCK_IMAGE_VER}
    network_mode: host
