version: "2"

services:
  jason-files-server:
    container_name: jason-files-server
    image: nginx
    network_mode: host
    volumes:
      - ./tests/e2e/index.html:/usr/share/nginx/html/index.html:ro
      - ./jason/pkg:/usr/share/nginx/html/pkg:ro
      - ./tests/e2e/nginx.conf:/etc/nginx/nginx.conf:ro

  control-api-mock:
    container_name: medea-control-api-mock
    build: mock
    depends_on:
      - medea
    image: ${MEDEA_CONTROL_MOCK_IMAGE_NAME}:${MEDEA_CONTROL_MOCK_IMAGE_VER}
    network_mode: host
