version: "2"

services:
  medea:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    image: ${COMPOSE_IMAGE_NAME}:${COMPOSE_IMAGE_VER}
    build: .
    depends_on: ["coturn"]
    environment:
      RUST_LOG: ${RUST_LOG}
      MEDEA_CONF: ${MEDEA_CONF}
      MEDEA_CONTROL__STATIC_SPECS_DIR: ${MEDEA_CONTROL__STATIC_SPECS_DIR}
    volumes:
      - ./${MEDEA_CONF}:/${MEDEA_CONF}:ro
      - ./${MEDEA_CONTROL__STATIC_SPECS_DIR}:/${MEDEA_CONTROL__STATIC_SPECS_DIR}:ro
    network_mode: host
  coturn:
    container_name: ${COMPOSE_PROJECT_NAME}-coturn
    image: instrumentisto/coturn:4.5
    command:
      - --log-file=stdout
    depends_on: ["coturn-db"]
    network_mode: host
    volumes:
      - ./_dev/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./.cache/coturn/data:/var/lib/coturn
  coturn-db:
    container_name: ${COMPOSE_PROJECT_NAME}-coturn-db
    image: redis:alpine
    command: ["redis-server", "/etc/redis.conf"]
    network_mode: host
    volumes:
      - ./_dev/coturn/redis.conf:/etc/redis.conf:ro
  control-api-mock:
    container_name: medea-control-api-mock
    build:
      context: .
      dockerfile: ./mock/control-api/Dockerfile
    image: ${MEDEA_CONTROL_MOCK_IMAGE_NAME}:${MEDEA_CONTROL_MOCK_IMAGE_VER}
    depends_on: ["medea"]
    network_mode: host
  jason-files-server:
    container_name: jason-files-server
    image: nginx:1.19.7-alpine
    network_mode: host
    volumes:
      - ./tests/e2e/index.html:/usr/share/nginx/html/index.html:ro
      - ./jason/pkg:/usr/share/nginx/html/pkg:ro
      - ./tests/e2e/nginx.conf:/etc/nginx/nginx.conf:ro
