version: "2"

services:
  jason-files-server:
    container_name: jason-files-server
    image: nginx
    network_mode: host
    volumes:
      - ./tests/e2e/index.html:/usr/share/nginx/html/index.html:ro
      - ./jason/pkg:/usr/share/nginx/html/pkg:ro
      - ./tests/e2e/nginx.conf:/etc/nginx/nginx.conf:ro
