[server]
# IP address to bind HTTP server to.
   bind_ip = "0.0.0.0"

# Port to bind HTTP server to.
   bind_port = 8080




[rpc]
# Duration, after which remote RPC client will be considered idle if no
# heartbeat messages received.
   idle_timeout = "10s"

# Duration, after which the server deletes the client session if
# the remote RPC client does not reconnect after it is idle.
   reconnect_timeout = "10s"




[turn]
# Turn server IP address.
   ip = "127.0.0.1"

# Turn server port.
   port = 3478

# Static user on Turn server.
   user = "USER"

# Static user password on Turn server.
   pass = "PASS"

[turn.db.redis]
# Host of Coturn's Redis database.
   host = "127.0.0.1"

# Port of Coturn's Redis database for client connections.
   port = 6379

# Password to connect to Coturn's Redis database with.
   pass = "turn"

# Number of Coturn's database in Redis.
   db_number = 0

# Timeout for establishing connection with Coturn's Redis database.
   connection_timeout = "5s"




[log]
# Maximum allowed level of application log entries.
#
# Possible values:
#   "OFF", "CRITICAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
   level = "DEBUG"




[shutdown]
# Maximum duration given to shutdown the whole application gracefully.
   timeout = "5s"
