[package]
name = "jason-hello-world"
version = "0.0.1"
edition = "2018"

[lib]
name = "jason"
crate-type = ["staticlib"]

[dependencies]
dart-sys = "2.0"
libc = "0.2"

[build-dependencies]
cc = "1.0"
