//! gRPC generated specs.
//! Don't edit `*.rs` files (except `lib.rs`) in this crate because it
//! automatically generated by `protoc` in `build.rs` file.

#![allow(bare_trait_objects)]
#![allow(clippy::pedantic)]
#![allow(clippy::cargo)]
#![allow(clippy::nursery)]

pub mod control;
pub mod control_grpc;
