#!/bin/bash
# Docker Hub post-push hook that is responsible to tag built image properly.

set -e

# Parse image name and tag.
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
origTag=${IMAGE_NAME:tagStart}

# For full-versioned tag provide minor/major versions and 'latest' tags.
if [[ "$origTag" == *"."*"."* ]]; then
  dot=$(expr index "$origTag" .)
  majorVer=${origTag:0:dot-1}

  rest=${origTag:dot}
  dot=$(expr index "$rest" .)
  minorVer="$majorVer.${rest:0:dot-1}"

  for tag in {"$minorVer","$majorVer",latest}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
  done
fi
