kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: webclient
spec:
  rules:
    - host: medea-demo.test
      http:
        paths:
          - path: /
            backend:
              serviceName: webclient
              servicePort: 80