kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: webclient
  labels:
    app: webclient
spec:
  rules:
    - host: medea-demo.test
      http:
        paths:
          - path: /
            backend:
              serviceName: webclient
              servicePort: 80
          - path: /
            backend:
              serviceName: medea
              servicePort: 8080