kind: Service
apiVersion: v1
metadata:
  name: medea
  labels:
    app: medea
    tier: backend
spec:
  selector:
    app: medea
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
