kind: Service
apiVersion: v1
metadata:
  name: webclient
  labels:
    app: webclient
    tier: frontend
spec:
  selector:
    app: webclient
    tier: frontend
  ports:
    - name: webclient-port
      port: 443
      targetPort: 80
