kind: Deployment
apiVersion: apps/v1
metadata:
  name: webclient
  labels:
    app: webclient
    tier: frontend
spec:
  serviceName: webclient
  replicas: 1
  selector:
    matchLabels:
      app: webclient
      tier: frontend
  template:
    metadata:
      labels:
        app: webclient
        tier: frontend
    spec:
      containers:
        - name: webclient
          image: instrumentisto/medea-demo:dev
          imagePullPolicy: IfNotPresent
