name: medea_jason
description: Cross-platform implementation of Medea media server client for Flutter.
version: 0.0.1
author: Instrumentisto Team
homepage: https://github.com/instrumentisto/medea

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_driver:
#    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.jason
        pluginClass: JasonPlugin
