//! gRPC generated specs.
//! Don't edit `*.rs` files in this module because it automatically generated by
//! `protoc` in `build.rs` file.

#![allow(clippy::pedantic)]
#![allow(clippy::cargo)]
#![allow(clippy::nursery)]

pub mod control;
pub mod control_grpc;
