name: CI

on: push

env:
  RUST_BACKTRACE: 1

jobs:

  ##########################
  # Linting and formatting #
  ##########################

  lint:
    name: Lint Rust code with Clippy

    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: make lint

  fmt:
    name: Verify Rust code style with rustfmt
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - run: make fmt check=yes




  ###########
  # Testing #
  ###########

  test-unit-medea-macro:
    name: Run medea-macro unit tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.unit crate=medea-macro

  test-unit-medea-reactive:
    name: Run medea-reactive unit tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.unit crate=medea-reactive

  test-unit-medea-coturn-telnet-client:
    name: Run medea-coturn-telnet-client unit tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.unit crate=medea-coturn-telnet-client

  test-unit-medea-client-api-proto:
    name: Run medea-client-api-proto unit tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.unit crate=medea-client-api-proto

  test-unit-medea:
    name: Run medea unit tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.unit crate=medea

  test-unit-medea-jason:
    name: Run medea-jason unit tests in Chrome and Firefox
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - name: Get wasm-bindgen-cli version from Cargo.lock
        run: echo "WASM_CLI_VERSION=$(cargo pkgid wasm-bindgen
                                      | grep -o '#.*'
                                      | grep -o '[0-9\.]*')"
             >> $GITHUB_ENV
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: ${{ env.WASM_CLI_VERSION }}
          use-tool-cache: true
      - name: Test in Chrome
        run: make test.unit crate=medea-jason browser=chrome
      - name: Test in Firefox
        run: make test.unit crate=medea-jason browser=firefox

  test-e2e:
    name: Run medea E2E tests
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make test.e2e up=yes dockerized=no




  ###########################
  # Documentation integrity #
  ###########################

  rustdoc:
    name: Check Rust docs of all crates
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      # Run all task sequentially to not flood the jobs list.
      - run: make docs.rust crate=medea-macro open=no
      - run: make docs.rust crate=medea-reactive open=no
      - run: make docs.rust crate=medea-coturn-telnet-client open=no
      - run: make docs.rust crate=medea-client-api-proto open=no
      - run: make docs.rust crate=medea-control-api-proto open=no
      - run: make docs.rust crate=medea open=no
      - run: make docs.rust crate=medea-jason open=no




  ##########################
  # Building and releasing #
  ##########################

  build-jason:
    name: Build medea-jason (stable)
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: make cargo.build crate=medea-jason dockerized=no debug=yes

  build-medea:
    name: Build medea (stable)
    if: |
      github.ref == 'refs/heads/master'
      || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: make cargo.build crate=medea dockerized=no debug=yes
