name: CI

on: push

env:
  RUST_BACKTRACE: 1

jobs:

  ###########
  # Testing #
  ###########

  test-e2e:
    name: E2E tests
    needs: ['docker']
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/medea-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1
        if: ${{ !contains(github.event.head_commit.message, '[fresh ci]') }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: test-e2e-{hash}
          restore-keys: test-e2e-
        continue-on-error: true
        if: ${{ !contains(github.event.head_commit.message, '[fresh ci]') }}

      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          use-tool-cache: true

      - uses: actions/download-artifact@v2
        with:
          name: docker-medea-${{ github.run_number }}
      - name: Unpack `medea` Docker image
        run: make docker.untar from-file=image.tar

      - uses: actions/download-artifact@v2
        with:
          name: docker-medea-control-api-mock-${{ github.run_number }}
      - name: Unpack `medea-control-api-mock` Docker image
        run: make docker.untar from-file=image.tar

      - name: Chrome1
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome2
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome3
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome4
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome5
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome6
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome7
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome8
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome9
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

      - name: Chrome10
        run: make test.e2e browser=chrome up=yes dockerized=yes tag=build-${{ github.run_number }}

  ############
  # Building #
  ############

  docker:
    name: Docker image
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/medea-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        include:
          - image: medea
            cache: false  # temporary disable caching due to CI issues
            #cache: ${{ github.ref != 'refs/heads/master'
            #           && !startsWith(github.ref, 'refs/tags/medea-')
            #           && !contains(github.event.head_commit.message, '[fresh ci]') }}
            export: true
            if: true

          - image: medea-control-api-mock
            cache: ${{ github.ref != 'refs/heads/master'
                       && !startsWith(github.ref, 'refs/tags/medea-control-api-mock-')
                       && !contains(github.event.head_commit.message, '[fresh ci]') }}
            export: true
            if: true

          - image: medea-demo
            cache: ${{ github.ref != 'refs/heads/master'
                       && !startsWith(github.ref, 'refs/tags/medea-demo-')
                       && !contains(github.event.head_commit.message, '[fresh ci]') }}
            export: ${{ startsWith(github.ref, 'refs/tags/medea-demo-') }}
            if: ${{ !startsWith(github.ref, 'refs/tags/medea-')
                    || startsWith(github.ref, 'refs/tags/medea-demo-')}}
          - image: medea-demo-edge
            cache: false  # temporary disable caching due to CI issues
            #cache: ${{ github.ref != 'refs/heads/master'
            #           && !contains(github.event.head_commit.message, '[fresh ci]') }}
            export: ${{ github.ref == 'refs/heads/master' }}
            if: ${{ !startsWith(github.ref, 'refs/tags/medea-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.if }}
      - uses: docker/setup-buildx-action@v1
        if: ${{ matrix.if }}

      - run: make docker.build debug=no no-cache=yes
                  image=${{ matrix.image }} tag=build-${{ github.run_number }}
        if: ${{ matrix.if && !matrix.cache }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-${{ matrix.image }}-build-{hash}
          restore-keys: docker-${{ matrix.image }}-build-
        continue-on-error: true
        timeout-minutes: 10
        if: ${{ matrix.if && matrix.cache }}
      - run: make docker.build debug=yes no-cache=no
                  image=${{ matrix.image }} tag=build-${{ github.run_number }}
        if: ${{ matrix.if && matrix.cache }}

      - run: make docker.tar to-file=image.tar
                  image=${{ matrix.image }} tags=build-${{ github.run_number }}
        if: ${{ matrix.if && matrix.export }}
      - uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.image }}-${{ github.run_number }}
          path: image.tar
          retention-days: 1
        if: ${{ matrix.if && matrix.export }}
