name: Debug

on: push

env:
  RUST_BACKTRACE: 1

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1

  job2:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/medea-')
    steps:
      - run: echo 2

  release-cargo-crate:
    name: Release on crates.io
    #if: |
    #  startsWith(github.ref, 'refs/tags/medea-')
    needs: ['job1', 'job2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse crate name and version
        id: crate
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: refs/tags/medea-test-0.1.0-alpha.2+dev   #${{ github.ref }}
          regex: '^refs/tags/(medea-[a-z-]*)-([0-9]+\.[0-9]+\.[0-9]+-?.*)$'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Release ${{ steps.crate.outputs.group2 }} version
              of ${{ steps.crate.outputs.group1 }} to crates.io
        run: echo "${{ steps.crate.outputs.group2 }} -> ${{ steps.crate.outputs.group1 }}"
